"""add prato_id to MetaDesperdicio

Revision ID: 6e1b821db935
Revises: 955fcb29fa81
Create Date: 2025-05-22 09:35:55.483944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e1b821db935'
down_revision = '955fcb29fa81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meta_desperdicio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prato_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_meta_desperdicio_prato_id', 'prato', ['prato_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meta_desperdicio', schema=None) as batch_op:
        batch_op.drop_constraint('fk_meta_desperdicio_prato_id', type_='foreignkey')
        batch_op.drop_column('prato_id')

    # ### end Alembic commands ###
