"""initial migration

Revision ID: 955fcb29fa81
Revises: 
Create Date: 2025-05-22 09:31:05.196269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '955fcb29fa81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('unidade', sa.String(length=5), nullable=False, server_default='UN'))
    op.drop_column('produto', 'unidade_medida')

    op.add_column('registro_desperdicio', sa.Column('unidade', sa.String(length=10), nullable=False, server_default='UN'))
    op.drop_column('registro_desperdicio', 'unidade_medida')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro_desperdicio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidade_medida', sa.VARCHAR(length=10), nullable=False))
        batch_op.drop_column('unidade')

    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidade_medida', sa.VARCHAR(length=5), nullable=False))
        batch_op.drop_column('unidade')

    op.create_table('_alembic_tmp_produto',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=20), nullable=True),
    sa.Column('nome', sa.VARCHAR(length=100), nullable=False),
    sa.Column('descricao', sa.TEXT(), nullable=True),
    sa.Column('preco_unitario', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('estoque_minimo', sa.FLOAT(), nullable=True),
    sa.Column('estoque_atual', sa.FLOAT(), nullable=True),
    sa.Column('data_cadastro', sa.DATETIME(), nullable=True),
    sa.Column('data_atualizacao', sa.DATETIME(), nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), nullable=True),
    sa.Column('categoria', sa.VARCHAR(length=50), nullable=True),
    sa.Column('marca', sa.VARCHAR(length=50), nullable=True),
    sa.Column('fornecedor_id', sa.INTEGER(), nullable=True),
    sa.Column('unidade', sa.VARCHAR(length=5), nullable=False),
    sa.CheckConstraint('estoque_atual >= 0', name='check_estoque_positivo'),
    sa.CheckConstraint('estoque_minimo >= 0', name='check_estoque_minimo_positivo'),
    sa.CheckConstraint('preco_unitario >= 0', name='check_preco_positivo'),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    # ### end Alembic commands ###
